trigger:
  branches:
    include:
      - main

pool:
  name: RotiPrataPool

steps:
- checkout: self

- script: |
    echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  displayName: Docker Hub login
  env:
    DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
    DOCKERHUB_TOKEN: $(DOCKERHUB_TOKEN)

- script: |
    docker build -t cs203/backend:latest -f Dockerfile.backend .
    docker push cs203/backend:latest
  displayName: Build and push backend

- script: |
    docker build -t cs203/frontend:latest -f frontend/Dockerfile.frontend ./frontend
    docker push cs203/frontend:latest
  displayName: Build and push frontend

- script: |
    cd /home/RotiPrata
    echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    docker compose pull
    docker compose up -d
    docker image prune -f
  displayName: Deploy on VM
  env:
    DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
    DOCKERHUB_TOKEN: $(DOCKERHUB_TOKEN)